### ISSUE TITLE
concat_osx.sh is hanging . . . maybe

### ISSUE THREAD

**Issue by tandrewnichols** [icholy/ttygif#34]
Kind of a two part issue. First, and most pressing, it _appears_ that `concat_osx.sh` is hanging. I see "creating animated gif: output.gif", but it never completes. Not sure how long it should take . . . but I let it run for like 45 minutes and still nothing. And then a second related issue, or feature request rather, would be additional logging . . . perhaps a progress bar or something. Anything to let the user know that something is indeed happening.

**Comment by tandrewnichols** [comment]
Here's a clip of the output. There's also that `rm: missing operand` thing . . . which, looking at the script itself, seems like it _has_ to be that `$pngs` is empty, but I don't see how that could be.

![screen shot 2015-06-17 at 10 59 15 pm](https://cloud.githubusercontent.com/assets/2755760/8223361/90bd2308-1544-11e5-9158-9c1cd153f5c8.png)

**Comment by icholy** [comment]
How long is the recording?

**Comment by tandrewnichols** [comment]
Maybe 10 to 15 seconds. I realize that's pretty long for gif. That's why I wondered how long it normally took.

**Comment by icholy** [comment]
That's not long at all. It should work fine. I'll check it out tomorrow.

**Comment by icholy** [comment]
Are the screencaptures being created in the directory?

**Comment by tandrewnichols** [comment]
Yes, a huge list of them.

**Comment by icholy** [comment]
I don't have OSX to test on, so can you `echo` the `$pngs` variable after [this](https://github.com/icholy/ttygif/blob/789104800a14e82bf79c596bb376bada79cbe939/concat_osx.sh#L8) line and make sure it's not empty.

**Comment by tandrewnichols** [comment]
Yeah, I actually tried that last night, and it worked. They were there.

**Comment by icholy** [comment]
echo [this](https://github.com/icholy/ttygif/blob/789104800a14e82bf79c596bb376bada79cbe939/concat_osx.sh#L43) line before it gets evaluated.

**Comment by tandrewnichols** [comment]
Ok, I'm gonna have to rerun the ttyrec and ttygif steps. The last time I ran it I used the code here on github, so it did successfully blow away my pngs when I ctrl-c'd (but still didn't finish the gif).

**Comment by tandrewnichols** [comment]
Should I be using the version from github or the version that I got when I ran `brew install https://raw.githubusercontent.com/icholy/ttygif/master/ttygif.rb`?

**Comment by icholy** [comment]
Try the one on github.

**Comment by tandrewnichols** [comment]
Ok, running the setup stuff now.

**Comment by icholy** [comment]
Hold up. Do you have `convert` aliased to something maybe? run `which convert`.

**Comment by tandrewnichols** [comment]
No, I don't have it aliased.

```
$ which convert
/usr/local/bin/convert

$ convert --version
Version: ImageMagick 6.9.1-1 Q16 x86_64 2015-04-15 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png zlib
```

Output of convert_osx.sh (truncated) is: 

```
convert -loop 0  -delay 53.8 ./00001_3.png -delay 77.5 ./00002_538.png -delay 14.3 ./00003_775.png -delay 8.0 ./00004_143.png -delay 17.6 ./00005_80.png -delay 7.9 ./00006_176.png -delay 7.1 ./00
007_79.png -delay 7.2 ./00008_71.png -delay 8.7 ./00009_72.png -delay 5.5 ./00010_87.png -delay 10.4 ./00011_55.png -delay 11.1 ./00012_104.png -delay 15.1 ./00013_111.png -delay 8.0 ./00014_151.
png -delay 11.2 ./00015_80.png -delay 23.1 ./00016_112.png -delay 17.6 ./00017_231.png -delay 17.6 ./00018_176.png -delay 5.5 ./00019_176.png -delay 8.8 ./00020_55.png -delay 12.7 ./00021_88.png 
-delay 56.7 ./00022_127.png -delay .1 ./00023_567.png -delay 0 ./00024_1.png -delay .1 ./00025_0.png -delay .1 ./00026_1.png -delay 585.5 ./00027_1.png -delay 0 ./00028_5855.png -delay 0 ./00029_
0.png -delay 5.4 ./00034_0.png -delay 0 ./00037_54.png -delay 0 ./00038_0.png -delay 5.3 ./00042_0.png -delay 0 ./00046_53.png -delay 0 ./00047_0.png -delay 3.1 ./00050_0.png -delay 0 ./00055_31.png -delay 0 ./00056_0.png -delay .1 ./00058_0.png -delay .3 ./00063_1.png -delay 0 ./00064_3.png -delay 0 ./00065_0.png -delay .3 ./00067_0.png -delay 0 ./00073_3.png -delay 0./00074_0.png -delay 0 ./00075_0.png -delay 3.3 ./00081_0.png -delay 0 ./00082_33.png -delay 0 ./00083_0.png -delay .8 ./00089_0.png -delay 0 ./00091_8.png -delay 0 ./00092_0.png -delay 2.6 ./00097_0.png -delay 0 ./00100_26.png -delay .8 ./00101_0.png -delay 0 ./00102_8.png -delay 0 ./00103_0.png -delay 1.2 ./00107_0.png -delay 0 ./00109_12.png -delay 0 ./00110_0.png -delay 2.2 ./00115_0.png -delay 0 ./00118_22.png -delay 0 ./00119_0.png -delay 20.6 ./00123_0.png -delay 0 ./00127_206.png -delay 0 ./00128_0.png -delay 1.7 ./00131_0.png -delay 0 ./00136_17.png -delay 0 ./00137_0.png -delay 1.9 ./00139_0.png -delay 0 ./00145_19.png -delay 0 ./00146_0.png -delay 0 ./00147_0.png -delay 1.7 ./00153_0.png -delay 0 ./00154_17.png -delay 0 ./00155_0.png -delay .7 ./00161_0.png -delay 0 ./00163_7.png -delay 0 ./00164_0.png -delay .9 ./00169_0.png -delay 0 ./00172_9.png -delay 0 ./00173_0.png -delay .8 ./00177_0.png -delay 0 ./00181_8.png -delay 0 ./00182_0.png -delay .7 ./00185_0.png -delay 0 ./00190_7.png -delay 0 ./00191_0.png -delay .4 ./00193_0.png -delay 0 ./00199_4.png  . . . -layers Optimize output.gif
```

**Comment by icholy** [comment]
Can you try running that command as-is and then with just a few of the screenshots?

**Comment by tandrewnichols** [comment]
Yeah, I made a smaller demo to see if I could get it to work.

**Comment by tandrewnichols** [comment]
Here's a smaller one:

```
convert -loop 0  -delay 54.0 ./00001_3.png -delay 51.0 ./00002_540.png -delay 6.3 ./00003_510.png -delay 7.9 ./00004_63.png -delay 6.4 ./00005_79.png -delay 13.5 ./00006_64.png -delay 7.2 ./00007_135.png -delay 8.8 ./00008_72.png -delay 8.7 ./00009_88.png -delay 3.2 ./00010_87.png -delay 10.3 ./00011_32.png -delay 12.8 ./00012_103.png -delay 7.2 ./00013_128.png -delay 19.9 ./00014_72.png -delay 23.2 ./00015_199.png -delay .2 ./00016_232.png -delay 29.3 ./00017_2.png -delay 22.4 ./00018_293.png ./00019_224.png -layers Optimize output.gif
```

**Comment by tandrewnichols** [comment]
And that worked (I mean using "concat_osx", not the command directly). So . . . maybe it's just really slow? Or is there a limit to the number of files?

**Comment by icholy** [comment]
So how long was the recording in the longer video and how many images did it result in?

**Comment by tandrewnichols** [comment]
I don't know exactly how long. I think I said 10 to 15 originally. Maybe it was longer than that, but not _a lot_ longer than that. I was intentionally trying to keep it short. It did create a lot of images though, as you can see in that command above. It took 4 screen grabs to copy them all (but then I ended up truncating them because it seemed ridiculous to paste that much in).

**Comment by icholy** [comment]
Can I have the recording file?

**Comment by tandrewnichols** [comment]
The longer one or the short one?

**Comment by icholy** [comment]
The one that doesn't work.

**Comment by tandrewnichols** [comment]
How can I get it to you? Github only allows images.

**Comment by icholy** [comment]
Send it to my email: ilia.choly@gmail.com

**Comment by tandrewnichols** [comment]
Sent.

**Comment by icholy** [comment]
@tandrewnichols I never got it.

**Comment by tandrewnichols** [comment]
Junk mail? I definitely sent it, and I just double checked the address. ![screen shot 2015-06-23 at 9 58 24 am](https://cloud.githubusercontent.com/assets/2755760/8307771/7fb37ac8-198e-11e5-8cc6-1d0ede0882fc.png)

**Comment by icholy** [comment]
Ok got it. Basically the recording has too many frames which results in too many images for `convert` to handle. Try the `skip_fix` branch I just created.

**Comment by tandrewnichols** [comment]
Ok. Might not get to it right away. We just had a baby.

**Comment by icholy** [comment]
No rush. and congrats! :tada: :congratulations:

**Comment by tandrewnichols** [comment]
Sorry, I had forgotten about this. I will try to do this soonish.

**Comment by tandrewnichols** [comment]
Hey @icholy, sorry for the delay. I never came back to this because I haven't needed a screen gif in a while, but I tried it this morning using the `skip_fix` branch, and it worked fine. Thanks!
