### ISSUE TITLE
readme.md references a bad concat_osx.sh

### ISSUE THREAD

**Issue by prophittcorey** [icholy/ttygif#36]
When doing this line on OS X:

`brew install https://raw.githubusercontent.com/icholy/ttygif/master/ttygif.rb`

I noticed the installed version was out of date with master. It looks like it was missing the `rm $pngs` fix and was instead doing `rm $gifs`. 

I cannot confirm if this was specific to my system or not (I had installed ttygif in the past so it may have not overwrote the old installed script).

**Comment by icholy** [comment]
I'll accept a PR.

**Comment by prophittcorey** [comment]
This was an old file on my system that caused the problem. Sorry!

**Comment by icholy** [comment]
@prophittcorey hey, I just pushed a bunch of changes and don't have a mac to test it on. Can you give it a shot maybe?
