### ISSUE TITLE
convert: unable to load module

### ISSUE THREAD

**Issue by arjunmayilvaganan** [icholy/ttygif#37]
Followed instructions without any change. But the following error seems to pop up:

https://gist.github.com/arjunmayilvaganan/e5202777888c9d37ca63

**Comment by icholy** [comment]
What are you doing to get this error? When does this happen?

**Comment by arjunmayilvaganan** [comment]
I'm on OS X 10.10.5.
I did install all the dependencies using Homebrew. Then created a ttyrec recording.
And, this error turns up, when i do,

`./ttygif myrecording`

**Comment by icholy** [comment]
I don't use OSX so I can't help. This seems like an issue with homebrew though. The ImageMagic dependency did not get installed correctly.

**Comment by arjunmayilvaganan** [comment]
Ok, actually this time i used the `-f` flag.
Lots of those .png images were generated. But When I tried to concatenate, the same above error popped up once for each of those generated .png images.
Anyhow, I'll try tweaking ImageMagic.

**Comment by arjunmayilvaganan** [comment]
When I do `identify -list format`, as per the second answer in http://stackoverflow.com/questions/9586048/imagemagick-no-decode-delegate,
.png format alone doesn't seem to appear in the list. But all other formats do.
However, now I'm closing this issue.
