### ISSUE TITLE
iTerm2 issue

### ISSUE THREAD

**Issue by raine** [icholy/ttygif#38]
`ttygif` gives:

```
20:22: execution error: iTerm got an error: Can’t get id of window 1. (-1728)
snapshot: Undefined error: 0
```

`Build 2.9.20150826-nightly`

**Comment by raine** [comment]
Seems to work in iTerm2 `Build 2.1.1`!

**Comment by icholy** [comment]
@raine hey, I just pushed a bunch of changes. I don't have an OSX machine to test on. Can you give it a shot maybe?
