### ISSUE TITLE
Something is wrong when make gifs.

### ISSUE THREAD

**Issue by zhenweiwang1990** [icholy/ttygif#4]
sh: 1: Syntax error: "(" unexpected
snapshot: Success

OS:Ubuntu 13.04 x64

**Comment by sholsapp** [comment]
Is there any way to fix this restriction so that you don't need a locally running X server? I'm confused why one can capture a termcast remotely, but not render the gifs remotely.

**Comment by icholy** [comment]
@sholsapp it takes screenshots using the `import` tool. This requires X.
