### ISSUE TITLE
29:31: execution error: Can’t get application "Apple_Terminal". (-1728)

### ISSUE THREAD

**Issue by Miserlou** [icholy/ttygif#46]
~/tty $ ttyrec myrecording
~/tty $ ttygif myrecording

29:31: execution error: Can’t get application "Apple_Terminal". (-1728)
Error: Failed to take snapshot: Undefined error: 0
Creating Animated GIF ... this can take a while
convert: no images defined `tty.gif' @ error/convert.c/ConvertImageCommand/3241.
Error: Failed to execute 'convert' command: Undefined error: 0
Created: tty.gif in the current directory!

OSX. Any ideas?

**Comment by icholy** [comment]
I don't have a Mac to test on, but it seems like it's failing to get the window id of the terminal application. I'll take a closer look at this on Tuesday.

**Comment by JasonRShaver** [comment]
I'm having the same issue on OSX 10.11.4.  I tried setting it up to use iTerm2 instead of Terminal (on a lark) and had the same issue with trying to get the WindowId

**Comment by icholy** [comment]
@JasonRShaver  have you tried compiling the latest version?

**Comment by JasonRShaver** [comment]
@icholy Just cloned and built and it worked great!  Thanks much!
