### ISSUE TITLE
No environment variable WINDOWID

### ISSUE THREAD

**Issue by davelupt** [icholy/ttygif#48]
For some reason I kept getting an error about the env var WINDOWID not being set. To remedy this, on Xubuntu I was able to do:
`export WINDOWID=$(xdotool getwindowfocus)`
After that everything worked.

**Comment by icholy** [comment]
`xdotool` is not installed by default, so wouldn't be keen on depending on it. Maybe we can add something to the README about it.

**Comment by davelupt** [comment]
That or having something in the error message as to the nature of what WINDOWID is and how to set it. It didn't take too long, but sometimes duckduckgo/google will steer you in the wrong direction.

**Comment by icholy** [comment]
I'm open to pull requests.

**Comment by davelupt** [comment]
I've generated the following [pull request](https://github.com/icholy/ttygif/pull/49).
