### ISSUE TITLE
`xwd` not found error

### ISSUE THREAD

**Issue by gabmontes** [icholy/ttygif#50]
I had no `xwd` command in my Debian system, so had to `sudo apt-get install x11-apps`. Please consider adding a note to the installation instructions.

Thanks!

**Comment by icholy** [comment]
I'll accept a PR.

**Comment by gabmontes** [comment]
Just opened PR #51.

Thanks again!

**Comment by icholy** [comment]
Thanks for the PR :)

**Comment by ryukinix** [comment]
Hmm, this utils is provide by other package too? I don't found `x11-apps` in the ArchLinux repositories... (searching alias name)

**Comment by icholy** [comment]
If you're using arch, you don't need hand holding. Try google.

**Comment by ryukinix** [comment]
I found. Is called `xorg-xwd`. If someone have problems with it, that is the package.

**Comment by claudiodangelis** [comment]
Thanks for hand holding, @ryukinix.

**Comment by huzhifeng** [comment]
In my case, I need to `sudo yum install -y xorg-x11-apps` for CentOS 7.2
