### ISSUE TITLE
Why so much memory on the conversion? My system consumes over %95 RAM during ttygif translation

### ISSUE THREAD

**Issue by ryukinix** [icholy/ttygif#52]
If I have a browser activate, I has good chances to frozen my system. (4GB RAM)

By the way, after multiple executions, I cannot more use again `ttygif`. I receive a traceback whose bash: `xwd: No space left on device`.

Appears some garbage is keeped. By the way, my swap memory don't downs after the execution. 

Ps.: Linux here.

**Comment by icholy** [comment]
You're probably making really long gifs.
Intermediate images are kept in the `/tmp/` directory.

**Comment by ryukinix** [comment]
10seconds is so long?

**Comment by icholy** [comment]
don't like it, don't use it.
