### ISSUE TITLE
Error: failed to exec screencapture

### ISSUE THREAD

**Issue by fate-lovely** [icholy/ttygif#55]
I pulled the latest version and got this error:

![image](https://cloud.githubusercontent.com/assets/4210829/16360560/b1d1c1f0-3b9c-11e6-9a04-b34fb3cd3b56.png)
 
it seems that screencapture can't accept `-l(null)`. I removed this param in `ttygif.c` and ttygif works fine. So, what's the point of `-l(null)`?

**Comment by icholy** [comment]
That's supposed to be window Id of the terminal. Can you try again with the last eat master? If that doesn't work I'll need to borrow my friends MacBook to test with.

**Comment by fate-lovely** [comment]
It's the latest master which produced the error. When I removed the `-l%s` param in `ttygif.c` I got the ttygif work, So I think it's not necessary to pass window ID.

**Comment by icholy** [comment]
It matters unless you have it full screen I think

**Comment by icholy** [comment]
Gonna test with my buddies computer, I'll get back to you tho.

**Comment by icholy** [comment]
try it now

**Comment by fate-lovely** [comment]
@icholy It works! Thank you for this great project.

**Comment by icholy** [comment]
glad you found it useful :smiley:
