### ISSUE TITLE
ttygif: myrecording: No such file or directory

### ISSUE THREAD

**Issue by reiz** [icholy/ttygif#68]
I just installed it with: 

```
brew install ttygif
```

That worked successfully. But when I run: 

```
ttygif myrecording -f
```

I get the error message: 

```
ttygif: myrecording: No such file or directory
```

What I'm doing wrong?

**Comment by icholy** [comment]
You need to use `ttyrec` to create the recording file first.

**Comment by reiz** [comment]
Thx. Resolved now.
