### ISSUE TITLE
ttyrec helper

### ISSUE THREAD

**Issue by FedericoCeratto** [icholy/ttygif#72]
Thanks for developing ttygif. It would be very convenient to have a ttyrec wrapper that runs a set of commands with a configurable pause between them and at the end and then calls ttygif on the output.

**Comment by icholy** [comment]
Eh, doesn't really seem worth it IMO.

``` sh
#!/bin/sh

ttyrec recording
ttygif recording
rm recording
```

**Comment by icholy** [comment]
This is beyond the scope of what ttygif is. Seems more like a ttyrec feature request.
