### ISSUE TITLE
Crashing mid conversion

### ISSUE THREAD

**Issue by maus-** [icholy/ttygif#75]
, 337C writtenX Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x4200001
  Serial number of failed request:  217
  Current serial number in output stream:  218
failed to execute: xwd -id 65011716 -out /tmp/ttygif.vPrtty/193.xwd

Running 16.04 on i3wm-gaps

**Comment by icholy** [comment]
Reproducible??

**Comment by maus-** [comment]
Yep, routinely crashes. I can send you the source ttyrec file / any debug info you need.

**Comment by maus-** [comment]
Ah ffs - this might just be the ttyrec files corrupting
