### ISSUE TITLE
Get error when install ttygit in arch i686

### ISSUE THREAD

**Issue by wsdjeg** [icholy/ttygif#77]
```
==> ERROR: ttygif is not available for the 'i686' architecture.

==> ERROR: An unknown error has occurred. Exiting...
```
when run `makepkg -is` in ttygit repo, I get these errors

**Comment by icholy** [comment]
@polyzen ?

**Comment by polyzen** [comment]
@wsdjeg, build with `makepkg -Ais`. The PKGBUILD has `arch=('x86_64')` as that's the only architecture it's been tested on. If it works for you, I will add i686.

>-A, --ignorearch
>    Ignore a missing or incomplete arch field in the build script. This is for rebuilding packages from source when the PKGBUILD may be slightly outdated and not updated with an arch=('yourarch') field.

**Comment by wsdjeg** [comment]
I will test it latter.

**Comment by wsdjeg** [comment]
![tty](https://user-images.githubusercontent.com/13142418/27736560-3cd16a14-5dd7-11e7-880e-4135c30acb3b.gif)

seems it works well for me.

**Comment by polyzen** [comment]
Great. Will update the package momentarily.

**Comment by icholy** [comment]
Has this been resolved?

**Comment by wsdjeg** [comment]
but I found a issue:
1. run `ttyrec test`
2.  then run `vim foo.txt`

the vim's screen is too small,

**Comment by icholy** [comment]
@wsdjeg I don't understand.

**Comment by wsdjeg** [comment]
here is a picture, the is only 1/4 of the terminal


![2017-07-07-21 17 50](https://user-images.githubusercontent.com/13142418/27961174-79082b38-6360-11e7-9bdd-ca6770672299.png)

**Comment by icholy** [comment]
You have to keep it the same size as when you recorded it.

**Comment by wsdjeg** [comment]
I do not change the terminal size when run `ttyrec` and `vim` it is a i3-wm windows (only one window)

**Comment by icholy** [comment]
Does it look right when you use `ttyplay`?

**Comment by wsdjeg** [comment]
ttyplay is same, the vim is 1/4 of terminal

**Comment by wsdjeg** [comment]
here is vedio:
https://asciinema.org/a/ekn5zSNDk0zL1nBjKhCdZwJ3u

**Comment by icholy** [comment]
@wsdjeg then that's an issue with ttyrec, can't help you.

**Comment by wsdjeg** [comment]
Thanks.

**Comment by wsdjeg** [comment]
clossing. If I found solution, I will post here.

**Comment by wsdjeg** [comment]
@icholy I found a post about it, here is a link:

http://raf.zyks.org/2017-07-06-termcasting.html
