### ISSUE TITLE
Custom playback speed

### ISSUE THREAD

**Issue by radiovisual** [icholy/ttygif#78]
Nice work on this fork of ttygif, btw.

I have a question (or feature request?): Is it possible to change the final playback speed of the resulting gif? I sometimes have the issue where I type slow in my demos, and I don't want to re-record just for the sake of trying to speed things up. If there was a way to customize the playback speed of the resulting gif, that would be awesome.

**Comment by icholy** [comment]
I'll add it when I have time. Contributions are welcome.

**Comment by hrobeers** [comment]
Is this issue fully resolved by #83 ?
