### ISSUE TITLE
Incorrect capture: tqdm progress bar 

### ISSUE THREAD

**Issue by adl1995** [icholy/ttygif#82]
I'm using the [tqdm](https://github.com/tqdm/tqdm) progress bar to show download progress in my [hips](http://github.com/hipspy/hips) package. However, after each iteration there is a line break (shown in the screenshot below). Is there any way to fix this?

![issue-ttygif](https://user-images.githubusercontent.com/13198325/30307287-7ca47bd8-9796-11e7-8ad4-e785b690a309.png)

**Comment by icholy** [comment]
Does it look right when you playback with `ttyplay <file>`?

**Comment by adl1995** [comment]
@icholy Yes, it does.

**Comment by icholy** [comment]
Can you get me a copy of the recording file you made?

**Comment by adl1995** [comment]
Sure, here it is. I had to zip it, as GitHub doesn't support binary format.

[tile-fetch.zip](https://github.com/icholy/ttygif/files/1294684/tile-fetch.zip)

**Comment by icholy** [comment]
@adl1995 when I run `ttyplay -s 10.0 tile-fetch` I'm seeing the line breaks like your picture above.

**Comment by adl1995** [comment]
@icholy I think I've figured out the problem. The line only breaks when I give `ttyplay` or `ttygif` command in windowed mode on my terminal. I just tried converting it to a GIF in full-screen mode and the line break is gone. Closing this issue now. Thanks!
