### ISSUE TITLE
Error on Centos7

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [icholy/ttygif#84]
when i execute the following command 
```
$ ttygif myrecording
```
the error information is :
```
failed to execute: xwd -id 31457286 -out /tmp/ttygif.Ln1Nqw/0.xwd
```

**Comment by icholy** [comment]
Do you have xwd installed? Also you. An use this over ssh, there has to be an X server running.

**Comment by zhaozhiyuan1989** [comment]
thanks , i resolve it by installing xwd : 
```
$ sudo yum install xwd
```
