### ISSUE TITLE
not working on fedora 27

### ISSUE THREAD

**Issue by raphaelsc** [icholy/ttygif#89]
[raphaelsc@Host-001 ~]$ export WINDOWID=23068679
[raphaelsc@Host-001 ~]$ ttyrec my
[raphaelsc@Host-001 ~]$ echo "test"
test
[raphaelsc@Host-001 ~]$ exit
[raphaelsc@Host-001 ~]$ ttygif my
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1600007
  Serial number of failed request:  9
  Current serial number in output stream:  10
failed to execute: xwd -id 23068679 -out /tmp/ttygif.qD6wY6/0.xwd

**Comment by icholy** [comment]
Are you sure that window id is right?

**Comment by raphaelsc** [comment]
I used the one suggested in README, i couldn't get it with that tool used on ubuntu, which i later realized it doesn't fit my graphic system. Any suggestions on how i could get it?

**Comment by icholy** [comment]
what do you mean by your graphics system?

**Comment by raphaelsc** [comment]
Sorry for not being specific, I mean GNOME. I'll play with it again the next days. I don't have a lot of time though :-( I'll keep you informed of my progress.

**Comment by icholy** [comment]
Should still work if you're using X. But you need the window id of the window you're trying to record. The one in the README is just an example that came from my machine.

**Comment by icholy** [comment]
@raphaelsc I'm closing this issue.
