### ISSUE TITLE
Install fail debian jessie stock

### ISSUE THREAD

**Issue by webdev23** [icholy/ttygif#90]
Well, following the installation procedure given on the main page.

![p6zj9vc](https://user-images.githubusercontent.com/2503337/37573738-5304352a-2b1b-11e8-88be-51ed5bedbb5f.png)

**Comment by icholy** [comment]
Does add std=c99 to CFLAGS  in the makefile fix it?

**Comment by webdev23** [comment]
It has worked, thanks. 
Now getting the `Error: WINDOWID environment variable was empty`, but there is no x in my env, as i use it on ssh.
Maybe this tool isn't made to run without a xserver?

**Comment by icholy** [comment]
It won't work without X installed.

**Comment by icholy** [comment]
Fixed in #91
