### ISSUE TITLE
failed to execute: convert -loop 0

### ISSUE THREAD

**Issue by jehy** [icholy/ttygif#92]
Full output:

> Creating Animated GIF ... this can take a while
> convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
> convert-im6.q16: cache resources exhausted `/tmp/ttygif.g6DnO1/40.xwd' @ error/cache.c/OpenPixelCache/3982.
> failed to execute: convert -loop 0  -delay 75.400000 /tmp/ttygif.g6DnO1/0.xwd -delay 4.800000 /tmp/ttygif.g6DnO1/1.xwd -delay 2.300000 /tmp/ttygif.g6DnO1/2.xwd -delay 26.400000 /tmp/ttygif.g6DnO1/3.xwd -delay 133.600000 /tmp/ttygif.g6DnO1/4.xwd -delay 7.200000 /tmp/ttygif.g6DnO1/5.xwd -delay 24.700000 /tmp/ttygif.g6DnO1/6.xwd -delay 30.400000 /tmp/ttygif.g6DnO1/7.xwd -delay 88.700000 /tmp/ttygif.g6DnO1/8.xwd -delay 20.700000 /tmp/ttygif.g6DnO1/9.xwd -delay 7.000000 /tmp/ttygif.g6DnO1/10.xwd -delay 104.000000 /tmp/ttygif.g6DnO1/11.xwd -delay 131.200000 /tmp/ttygif.g6DnO1/12.xwd -delay 14.300000 /tmp/ttygif.g6DnO1/13.xwd -delay 23.300000 /tmp/ttygif.g6DnO1/14.xwd -delay 7.000000 /tmp/ttygif.g6DnO1/15.xwd -delay 21.700000 /tmp/ttygif.g6DnO1/16.xwd -delay 112.500000 /tmp/ttygif.g6DnO1/17.xwd -delay 31.300000 /tmp/ttygif.g6DnO1/18.xwd -delay 0.200000 /tmp/ttygif.g6DnO1/19.xwd -delay 4.700000 /tmp/ttygif.g6DnO1/20.xwd -delay 6.500000 /tmp/ttygif.g6DnO1/21.xwd -delay 6.300000 /tmp/ttygif.g6DnO1/22.xwd -delay 11.300000 /tmp/ttygif.g6DnO1/23.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/24.xwd -delay 6.300000 /tmp/ttygif.g6DnO1/25.xwd -delay 9.300000 /tmp/ttygif.g6DnO1/26.xwd -delay 23.700000 /tmp/ttygif.g6DnO1/27.xwd -delay 18.000000 /tmp/ttygif.g6DnO1/28.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/29.xwd -delay 5.500000 /tmp/ttygif.g6DnO1/30.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/31.xwd -delay 5.100000 /tmp/ttygif.g6DnO1/32.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/33.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/34.xwd -delay 18.000000 /tmp/ttygif.g6DnO1/35.xwd -delay 16.300000 /tmp/ttygif.g6DnO1/36.xwd -delay 1.900000 /tmp/ttygif.g6DnO1/37.xwd -delay 0.000000 /tmp/ttygif.g6DnO1/38.xwd -delay 0.600000 /tmp/ttygif.g6DnO1/39.xwd -delay 102.800000 /tmp/ttygif.g6DnO1/40.xwd -delay 20.900000 /tmp/ttygif.g6DnO1/41.xwd -delay 20.700000 /tmp/ttygif.g6DnO1/42.xwd -delay 8.800000 /tmp/ttygif.g6DnO1/43.xwd -delay 39.900000 /tmp/ttygif.g6DnO1/44.xwd -delay 36.800000 /tmp/ttygif.g6DnO1/45.xwd -delay 31.100000 /tmp/ttygif.g6DnO1/46.xwd -delay 47.100000 /tmp/ttygif.g6DnO1/47.xwd -delay 7.700000 /tmp/ttygif.g6DnO1/48.xwd -delay 26.500000 /tmp/ttygif.g6DnO1/49.xwd -delay 7.200000 /tmp/ttygif.g6DnO1/50.xwd -delay 7.900000 /tmp/ttygif.g6DnO1/51.xwd -delay 38.400000 /tmp/ttygif.g6DnO1/52.xwd -delay 15.100000 /tmp/ttygif.g6DnO1/53.xwd -delay 15.100000 /tmp/ttygif.g6DnO1/54.xwd -delay 5.600000 /tmp/ttygif.g6DnO1/55.xwd -delay 22.400000 /tmp/ttygif.g6DnO1/56.xwd -delay 7.900000 /tmp/ttygif.g6DnO1/57.xwd -delay 100.800000 /tmp/ttygif.g6DnO1/58.xwd -delay 63.800000 /tmp/ttygif.g6DnO1/59.xwd -delay 0.100000 /tmp/ttygif.g6DnO1/60.xwd -delay 4.700000 /tmp/ttygif.g6DnO1/61.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/62.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/63.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/64.xwd -delay 5.200000 /tmp/ttygif.g6DnO1/65.xwd -delay 4.800000 /tmp/ttygif.g6DnO1/66.xwd -delay 5.100000 /tmp/ttygif.g6DnO1/67.xwd -delay 4.700000 /tmp/ttygif.g6DnO1/68.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/69.xwd -delay 0.400000 /tmp/ttygif.g6DnO1/70.xwd -delay 3.000000 /tmp/ttygif.g6DnO1/71.xwd -delay 0.900000 /tmp/ttygif.g6DnO1/72.xwd -delay 0.400000 /tmp/ttygif.g6DnO1/73.xwd -delay 0.700000 /tmp/ttygif.g6DnO1/74.xwd -delay 243.700000 /tmp/ttygif.g6DnO1/75.xwd -delay 86.400000 /tmp/ttygif.g6DnO1/76.xwd -delay 12.600000 /tmp/ttygif.g6DnO1/77.xwd -delay 13.700000 /tmp/ttygif.g6DnO1/78.xwd -delay 16.000000 /tmp/ttygif.g6DnO1/79.xwd -delay 13.500000 /tmp/ttygif.g6DnO1/80.xwd -delay 13.500000 /tmp/ttygif.g6DnO1/81.xwd -delay 68.600000 /tmp/ttygif.g6DnO1/82.xwd -delay 12.900000 /tmp/ttygif.g6DnO1/83.xwd -delay 16.700000 /tmp/ttygif.g6DnO1/84.xwd -delay 32.800000 /tmp/ttygif.g6DnO1/85.xwd -delay 55.900000 /tmp/ttygif.g6DnO1/86.xwd -delay 62.300000 /tmp/ttygif.g6DnO1/87.xwd -delay 26.300000 /tmp/ttygif.g6DnO1/88.xwd -delay 11.100000 /tmp/ttygif.g6DnO1/89.xwd -delay 22.200000 /tmp/ttygif.g6DnO1/90.xwd -delay 12.100000 /tmp/ttygif.g6DnO1/91.xwd -delay 76.700000 /tmp/ttygif.g6DnO1/92.xwd -delay 81.000000 /tmp/ttygif.g6DnO1/93.xwd -delay 0.200000 /tmp/ttygif.g6DnO1/94.xwd -delay 4.800000 /tmp/ttygif.g6DnO1/95.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/96.xwd -delay 5.200000 /tmp/ttygif.g6DnO1/97.xwd -delay 5.100000 /tmp/ttygif.g6DnO1/98.xwd -delay 5.100000 /tmp/ttygif.g6DnO1/99.xwd -delay 4.700000 /tmp/ttygif.g6DnO1/100.xwd -delay 5.100000 /tmp/ttygif.g6DnO1/101.xwd -delay 5.000000 /tmp/ttygif.g6DnO1/102.xwd -delay 4.900000 /tmp/ttygif.g6DnO1/103.xwd -delay 0.500000 /tmp/ttygif.g6DnO1/104.xwd -delay 3.100000 /tmp/ttygif.g6DnO1/105.xwd -delay 0.800000 /tmp/ttygif.g6DnO1/106.xwd -delay 0.400000 /tmp/ttygif.g6DnO1/107.xwd -delay 0.000000 /tmp/ttygif.g6DnO1/108.xwd -delay 0.800000 /tmp/ttygif.g6DnO1/109.xwd -delay 213.900000 /tmp/ttygif.g6DnO1/110.xwd -delay 100.000000 /tmp/ttygif.g6DnO1/111.xwd -layers Optimize tty.gif 2>&1

Ubuntu 17.10, using Konsole terminal.

**Comment by icholy** [comment]
> convert-im6.q16: cache resources exhausted

Looks like it ran out of memory.

**Comment by jehy** [comment]
I have 16GB RAM : )
But I exited shell after recording creation and it worked okay on second try.

**Comment by icholy** [comment]
strange
