### ISSUE TITLE
https:storage.googleapis.com

### ISSUE THREAD

**Issue by emb03** [icholy/ttygif#95]
when downloading via brew:

get this message:  DownloadError: Failed to download resource "webp"
Download failed: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.0.tar.gz

Storage.http://googleapis.com, a malicious site, is a tech scam support, created by cyber criminals to scam victims' money via showing bogus security alert and luring you into using provided paid online services. Usually, adware or malware can be conducive its appearance in your computer.

**Comment by icholy** [comment]
No it's not, it's Google's cloud storage. That webp link works fine for me, maybe check your firewall.
