### ISSUE TITLE
Failed creating new xdo instance

### ISSUE THREAD

**Issue by reillychase** [icholy/ttygif#96]
Hi!
Is this supposed to work over SSH or only locally?

I ran into the WINDOWID issue so I did "export WINDOWID=$(xdotool getwindowfocus)"

However, the output of xdotool getwindowfocus is an error which I have been unable to solve:

Error: Can't open display: (null)
Failed creating new xdo instance

Any feedback is appreciated!

**Comment by icholy** [comment]
It only works locally because it uses the X server. You can start it locally and then ssh to a remote server though.
