### ISSUE TITLE
too many images an issue

### ISSUE THREAD

**Issue by stevesmoot** [icholy/ttygif#99]
Creating Animated GIF ... this can take a while
failed to execute: convert -loop 0  -delay 72.00....
then pages and pages of images on the command line - suspect too many args for the command.  may want to restructure around xargs

**Comment by stevesmoot** [comment]
(68000 images in my case)

**Comment by icholy** [comment]
Can you post the output?

**Comment by stevesmoot** [comment]
It has scrolled away.  there were 6800 image files, so the command line to
assemble became too long, it's straightforward really.
-s

**Comment by icholy** [comment]
Let me know when you can give me something to work with.
